### ISSUE TITLE
microflo runtime cannot connect to Arduino Uno

### ISSUE THREAD

**Issue by lerobotquirevait** [microflo/microflo-example-arduino#1]
Hi,

After seen your reply @jonnor about building microflo, i tried [microflo-example-arduino](https://github.com/microflo/microflo-example-arduino) with your update documentation (Thanks for this)
Everythings were ok in "Setting up".
But, when i came to [Programming with Flowhub](https://github.com/microflo/microflo-example-arduino#programming-with-flowhub), i encounter some problems.
When i want to run microflo runtime with
`npm start`
i obtain this
```
> microflo-example-arduino@0.0.1 start /home/alexandre/Documents/microflo-example-arduino
> microflo runtime --graph graphs/blink.fbp --componentmap build/blink/componentlib-map.json

INFO: No runtime id set, generated one: afbade42-23b8-4824-8f98-08518b2421de
Using serial baudrate with auto 9600
Available serial ports:  [ '/dev/ttyACM0',
  '/dev/ttyS0',
  '/dev/ttyS1',
  '/dev/ttyS10',
  '/dev/ttyS11',
  '/dev/ttyS12',
  '/dev/ttyS13',
  '/dev/ttyS14',
  '/dev/ttyS15',
  '/dev/ttyS16',
  '/dev/ttyS17',
  '/dev/ttyS18',
  '/dev/ttyS19',
  '/dev/ttyS2',
  '/dev/ttyS20',
  '/dev/ttyS21',
  '/dev/ttyS22',
  '/dev/ttyS23',
  '/dev/ttyS24',
  '/dev/ttyS25',
  '/dev/ttyS26',
  '/dev/ttyS27',
  '/dev/ttyS28',
  '/dev/ttyS29',
  '/dev/ttyS3',
  '/dev/ttyS30',
  '/dev/ttyS31',
  '/dev/ttyS4',
  '/dev/ttyS5',
  '/dev/ttyS6',
  '/dev/ttyS7',
  '/dev/ttyS8',
  '/dev/ttyS9' ]
Using port: /dev/ttyACM0
[TimeoutError: Device did not respond within 1000ms]

npm ERR! Linux 4.10.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! microflo-example-arduino@0.0.1 start: `microflo runtime --graph graphs/blink.fbp --componentmap build/blink/componentlib-map.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the microflo-example-arduino@0.0.1 start script 'microflo runtime --graph graphs/blink.fbp --componentmap build/blink/componentlib-map.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the microflo-example-arduino package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     microflo runtime --graph graphs/blink.fbp --componentmap build/blink/componentlib-map.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs microflo-example-arduino
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls microflo-example-arduino
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alexandre/Documents/microflo-example-arduino/npm-debug.log
```

**npm bugs microflo-example-arduino** give me
```
npm ERR! Linux 4.10.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "microflo-example-arduino"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/microflo-example-arduino
npm ERR! 404 
npm ERR! 404  'microflo-example-arduino' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alexandre/Documents/microflo-example-arduino/npm-debug.log
```

The log file give 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'microflo-example-arduino' ]
2 info using npm@3.5.2
3 info using node@v4.7.2
4 silly fetchPackageMetaData microflo-example-arduino
5 silly fetchNamedPackageData microflo-example-arduino
6 silly mapToRegistry name microflo-example-arduino
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry uri https://registry.npmjs.org/microflo-example-arduino
10 verbose request uri https://registry.npmjs.org/microflo-example-arduino
11 verbose request no auth needed
12 info attempt registry request try #1 at 21:05:57
13 verbose request id 04434ff724a97680
14 http request GET https://registry.npmjs.org/microflo-example-arduino
15 http 404 https://registry.npmjs.org/microflo-example-arduino
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '2',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Tue, 11 Jul 2017 19:05:58 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   age: '0',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-lcy1130-LCY',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1499799958.765512,VS0,VE386',
16 verbose headers   vary: 'Accept-Encoding' }
17 silly get cb [ 404,
17 silly get   { 'content-type': 'application/json',
17 silly get     'cache-control': 'max-age=0',
17 silly get     'content-length': '2',
17 silly get     'accept-ranges': 'bytes',
17 silly get     date: 'Tue, 11 Jul 2017 19:05:58 GMT',
17 silly get     via: '1.1 varnish',
17 silly get     age: '0',
17 silly get     connection: 'keep-alive',
17 silly get     'x-served-by': 'cache-lcy1130-LCY',
17 silly get     'x-cache': 'MISS',
17 silly get     'x-cache-hits': '0',
17 silly get     'x-timer': 'S1499799958.765512,VS0,VE386',
17 silly get     vary: 'Accept-Encoding' } ]
18 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/microflo-example-arduino
18 silly fetchPackageMetaData     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
18 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
18 silly fetchPackageMetaData     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
18 silly fetchPackageMetaData     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
18 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
18 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
18 silly fetchPackageMetaData     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
18 silly fetchPackageMetaData     at emitOne (events.js:82:20)
18 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
18 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
18 silly fetchPackageMetaData  error for microflo-example-arduino { [Error: Registry returned 404 for GET on https://registry.npmjs.org/microflo-example-arduino]
18 silly fetchPackageMetaData   pkgid: 'microflo-example-arduino',
18 silly fetchPackageMetaData   statusCode: 404,
18 silly fetchPackageMetaData   code: 'E404' }
19 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/microflo-example-arduino
19 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
19 verbose stack     at emitTwo (events.js:87:13)
19 verbose stack     at Request.emit (events.js:172:7)
19 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
19 verbose stack     at emitOne (events.js:82:20)
19 verbose stack     at Request.emit (events.js:169:7)
19 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
20 verbose statusCode 404
21 verbose pkgid microflo-example-arduino
22 verbose cwd /home/alexandre/Documents/microflo-example-arduino
23 error Linux 4.10.0-21-generic
24 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "microflo-example-arduino"
25 error node v4.7.2
26 error npm  v3.5.2
27 error code E404
28 error 404 Registry returned 404 for GET on https://registry.npmjs.org/microflo-example-arduino
29 error 404
30 error 404 'microflo-example-arduino' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]
```

**Comment by jonnor** [comment]
That microflo-example-arduino is not in the NPM  registry is expected.

The more problematic is that Microflo on the microcontroller did not respond... Which microcontroller/board are you using?
The upload from Arduino was successful? Does the built in LED now blink around 3 times per second (default microflo graph)?

**Comment by lerobotquirevait** [comment]
I'm using an Arduino UNO.
Yes, the upload was successful. The Led blink well 3 times per second.

**Comment by jonnor** [comment]
Found the problem. This is same issue as in https://github.com/microflo/microflo/issues/133

**Comment by jonnor** [comment]
Should be now fixed in master. You will need to update. If you are using git on commandline can do `git pull origin/master` and then `npm install`. If not, remove the existing folder and follow the setup instructions again.
